config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'comics#index'
  resources :comics do
    collection do
      get :happy
      get :angry
      get :sad
      get :excite
    end
  end
  resources :stories ,only: %w(index show)
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
# frozen_string_literal: true
class Comic < ActiveRecord::Base
  belongs_to :story

  has_one_attached :image_url

  enum emotion_type: {
    happy: 0,
    angry: 1,
    sad: 2,
    excite: 3,
  }
end

app/models/product.rb
# frozen_string_literal: true
class Product < ActiveRecord::Base
  has_many :stories
end

app/models/story.rb
# frozen_string_literal: true
class Story < ActiveRecord::Base
  has_many :comics
  belongs_to :product
  has_one_attached :image_url
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comic.all.shuffle[0..9]
  end

  def show
    @comic = Comic.find(params["id"])
    comics = Comic.all
    @unlabeled_cnt = comics.where(emotion_type:nil).count
    @all_cnt = comics.count
  end

  def update
    comic = Comic.find(params["id"])
    comic.emotion_type = params["emotion_type"].to_i
    comic.save!
    redirect_to comic_path(Comic.where(emotion_type:nil).shuffle.first.id)
  end

  def happy
    @comics = Comic.where(emotion_type:"happy").shuffle[0..9]
  end

  def angry
    @comics = Comic.where(emotion_type:"angry").shuffle[0..9]
  end

  def sad
    @comics = Comic.where(emotion_type:"sad").shuffle[0..9]
  end

  def excite
    @comics = Comic.where(emotion_type:"excite").shuffle[0..9]
  end

  private

    def comic_params
      params.require(:comic).permit(:id, :emotin_type, :image_urle)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all.shuffle[0..1]
  end

  def show
    @story = Story.find_by(story_num:params["id"])
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/comics/angry.html.slim
h1 怒

- @comics.each do |comic|
  - if comic.image_url.attached?
    = image_tag url_for(comic.image_url)

app/views/comics/excite.html.slim
h1 楽

- @comics.each do |comic|
  - if comic.image_url.attached?
    = image_tag url_for(comic.image_url)

app/views/comics/happy.html.slim
h1 喜

- @comics.each do |comic|
  - if comic.image_url.attached?
    = image_tag url_for(comic.image_url)

app/views/comics/index.html.slim
h1 index(show random comics)

- @comics.each do |comic|
  - if comic.image_url.attached?
    = link_to(image_tag(url_for(comic.image_url)), comic_path(comic))

ul
  li
    = button_to '喜', 'comics/happy', class:"btn-lg btn-primary",method: :get
  li
    = button_to '怒', 'comics/angry', class:"btn-lg btn-danger",method: :get
  li
    = button_to '哀', 'comics/sad', class:"btn-lg btn-info",method: :get
  li
    = button_to '楽', 'comics/excite', class:"btn-lg btn-warning",method: :get

= button_to 'STORY', '/stories', class:"btn btn-link"

app/views/comics/sad.html.slim
h1 哀

- @comics.each do |comic|
  - if comic.image_url.attached?
    = image_tag url_for(comic.image_url)

app/views/comics/show.html.slim
h1 Show

h2 = "Story:#{@comic.story.story_num}話"
h3 = "分類: #{@comic.emotion_type || "未"}"
h3 = "進捗バー: #{@unlabeled_cnt} / #{@all_cnt}"
- if @comic.image_url.attached?
  = link_to(image_tag(url_for(@comic.image_url)), story_path(@comic.story.story_num))
span
  = button_to '喜', comic_path(emotion_type:0), method: :patch, class:"btn-lg btn-primary"
  = button_to '怒', comic_path(emotion_type:1), method: :patch, class:"btn-lg btn-danger"
  = button_to '哀', comic_path(emotion_type:2), method: :patch, class:"btn-lg btn-info"
  = button_to '楽', comic_path(emotion_type:3), method: :patch, class:"btn-lg btn-warning"

= button_to 'TOP', root_path, class:"btn btn-link" , method: :get

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickerPicker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/index.html.slim
h1 index(show random comics)

- @stories.each do |story|
  - if story.image_url.attached?
    = link_to(image_tag(url_for(story.image_url)), story_path(story))

= button_to 'TOP', '/comics', class:"btn btn-link"

app/views/stories/show.html.slim
h1 Show

h2 = "Story:#{@story.story_num}話"
- if @story.image_url.attached?
  = image_tag url_for(@story.image_url)

= button_to 'TOP', '/comics', class:"btn btn-link"